export REDDIT_CLIENT_ID=
export REDDIT_CLIENT_SECRET=
export REDDIT_PASSWORD=
export REDDIT_USERNAME=
export REDDIT_USER_AGENT=

export OPT_SUBREDDITS=
export OPT_COMMENT_LIMIT=
export OPT_SEARCH_START_HOURS_AGO=

export DB_USER=
export DB_PASSWORD=
export DB_PORT=
export DB_NAME=